services:
  redis:
    image: redis:7.4.2
    container_name: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./master/data:/data
      - ./master/conf:/usr/local/etc/redis
    network_mode: host

  sentinel:
    image: redis:7.4.2
    container_name: sentinel
    entrypoint: "/bin/bash  -c"
    command:
      - |
        chown redis:redis /usr/local/etc/redis/redis.conf 
        redis-server /usr/local/etc/redis/redis.conf --sentinel
    volumes:
      - ./sentinel/conf:/usr/local/etc/redis
    depends_on:
      - redis
    network_mode: host
